export const Failed = require('../assets/animation/failed.json')
export const Success = require('../assets/animation/success.json')
export const Loading = require('../assets/animation/loading.json')
export const FailedCard = require('../assets/animation/failedcard.json')
export const Complete = require('../assets/animation/complete.json')
export const Empty = require('../assets/animation/emptybox.json')